list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/score_panel/score_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/team_panel/team_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Bold_64__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_18__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_24__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_32__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_36__data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/ALG_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/ARG_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/AUS_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/AUT_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/background_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/BEL_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/BIH_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/BRA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/CAN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/CIV_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/COD_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/COL_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/CPV_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/CRO_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/CUW_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/CZE_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/ECU_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/EGY_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/ENG_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/ESP_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/FRA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/GER_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/GHA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/HAI_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/IRN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/IRQ_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/JOR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/JPN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/KOR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/KSA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/lvgl_logo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/MAR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/MEX_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/NED_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/NOR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/NZL_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/PAN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/PAR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/POR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/QAT_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/RSA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/SCO_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/SEN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/SUI_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/SWE_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/TUN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/TUR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/URY_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/USA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/UZB_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_main/screen_main_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_flag/wd_flag_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_flag/wd_flag_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_flag/wd_flag.c
  ${CMAKE_CURRENT_LIST_DIR}/worldcup_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/worldcup_ui.c)