list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/score_panel/score_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/team_panel/team_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Bold_64__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_18__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_24__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_32__data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/NS_Medium_36__data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/background_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_ALG_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_ARG_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_AUS_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_AUT_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_BEL_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_BIH_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_BRA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_CAN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_CIV_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_COD_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_COL_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_CPV_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_CRO_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_CUW_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_CZE_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_ECU_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_EGY_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_ENG_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_ESP_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_FRA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_GER_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_GHA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_HAI_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_IRN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_IRQ_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_JOR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_JPN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_KOR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_KSA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_MAR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_MEX_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_NED_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_NOR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_NZL_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_PAN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_PAR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_POR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_QAT_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_RSA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_SCO_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_SEN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_SUI_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_SWE_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_TUN_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_TUR_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_URY_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_USA_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flag_UZB_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/lvgl_logo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_main/screen_main_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_flag/wd_flag_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_flag/wd_flag_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_flag/wd_flag.c
  ${CMAKE_CURRENT_LIST_DIR}/worldcup_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/worldcup_ui.c)